module.exports = {
	content: ["./src/**/*.{js,jsx}", "node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}"],
	theme: {
		extend: {
			colors: {
				primary: "rgb(var(--color-primary) / <alpha-value>)",
				secondary: "rgb(var(--color-secondary) / <alpha-value>)",
				grey: {
					light: "rgb(var(--color-grey-light) / <alpha-value>)",
					DEFAULT: "rgb(var(--color-grey) / <alpha-value>)",
					dark: "rgb(var(--color-grey-dark) / <alpha-value>)",
				},
				alert: {
					info: {
						DEFAULT: "rgb(var(--color-info) / <alpha-value>)",
						dark: "rgb(var(--color-info-dark) / <alpha-value>)",
					},
					warning: {
						DEFAULT: "rgb(var(--color-warning) / <alpha-value>)",
						dark: "rgb(var(--color-warning-dark) / <alpha-value>)",
					},
					danger: {
						DEFAULT: "rgb(var(--color-danger) / <alpha-value>)",
						dark: "rgb(var(--color-danger-dark) / <alpha-value>)",
					},
				},
				focus: "rgb(var(--color-focus) / <alpha-value>)",
				button: {
					DEFAULT: "rgb(var(--color-button) / <alpha-value>)",
					dark: "rgb(var(--color-button-dark) / <alpha-value>)",
				},
				tooltip: "rgb(var(--color-tooltip) / <alpha-value>)",
				editor: "rgb(var(--color-editor) / <alpha-value>)",
				"editor-border": "rgb(var(--color-editor-border) / <alpha-value>)",
				"editor-toolbar": "rgb(var(--color-editor-toolbar) / <alpha-value>)",
				"editor-subtoolbar": "rgb(var(--color-editor-subtoolbar) / <alpha-value>)",
				editable: "rgb(var(--color-editable) / <alpha-value>)",
				"editable-border": "rgb(var(--color-editable-border) / <alpha-value>)",
			},
			fontFamily: {
				main: "var(--font-main)",
				"modal-title": "var(--font-modal-title)",
				"editor-arial": ["Arial", "Helvetica", "sans-serif"],
				"editor-brushScript": ["'Brush Script MT'", "cursive"],
				"editor-calibri": ["Calibri", "Candara", "Segoe", "'Segoe UI'", "Optima", "Arial", "sans-serif"],
				"editor-cambria": ["Cambria", "Georgia", "serif"],
				"editor-centuryGothic": ["'Century Gothic'", "CenturyGothic", "AppleGothic", "sans-serif"],
				"editor-consolas": ["Consolas", "monaco", "monospace"],
				"editor-courierNew": [
					"'Courier New'",
					"Courier",
					"'Lucida Sans Typewriter'",
					"'Lucida Typewriter'",
					"monospace",
				],
				"editor-copperplate": ["Copperplate", "'Copperplate Gothic Light'", "fantasy"],
				"editor-edel": ["Edel", "cursive"],
				"editor-escolar": ["Escolar", "cursive"],
				"editor-franklinGothic": ["'Franklin Gothic'", "'ITC Franklin Gothic'", "Arial", "sans-serif"],
				"editor-georgia": ["Georgia", "Times", "'Times New Roman'", "serif"],
				"editor-helvetica": ["'Helvetica Neue'", "Helvetica", "Arial", "sans-serif"],
				"editor-impact": [
					"Impact",
					"Haettenschweiler",
					"'Franklin Gothic Bold'",
					"Charcoal",
					"'Helvetica Inserat'",
					"'Bitstream Vera Sans Bold'",
					"'Arial Black'",
					"sans-serif",
				],
				"editor-lucida": ["'Lucida Sans'", "Geneva", "Verdana", "sans-serif"],
				"editor-papyrus": ["Papyrus", "fantasy"],
				"editor-TMR": ["'Times New Roman'", "Times", "serif"],
				"editor-trebuchet": [
					"'Trebuchet MS'",
					"'Lucida Grande'",
					"'Lucida Sans Unicode'",
					"'Lucida Sans'",
					"'Tahoma'",
					"sans-serif",
				],
				"editor-verdana": ["Verdana", "Geneva", "sans-serif"],
			},
			fontSize: {
				"navbar-link-text": "clamp(1.125rem, 5vw, 1.4rem)",
				"navbar-link-icon": "1.55rem",
				"modal-title": "clamp(1.3rem, 6vw, 1.75rem)",
				"modal-heading": "clamp(1.1rem, 4vw, 1.4rem)",
				"modal-base": "clamp(0.5rem, 2.5vw, 1rem)",
				"modal-base-lg": "clamp(0.7rem, 3vw, 1.2rem)",
				"modal-alert-box": "clamp(0.65rem, 2vw, 0.95rem)",
			},
			gridTemplateColumns: {
				"fluid-xs": "repeat(auto-fill, minmax(1rem, 2rem))",
				"fluid-sm": "repeat(auto-fill, minmax(2rem, 5rem))",
				fluid: "repeat(auto-fill, minmax(5rem, 10rem))",
				"fluid-md": "repeat(auto-fill, minmax(10rem, 15rem))",
				"fluid-lg": "repeat(auto-fill, minmax(15rem, 20rem))",
			},
		},
	},
	plugins: [require("flowbite/plugin")],
};
