# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AME - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Codigo
        
    steps:
    - name: Paso 1.0 - Checkout del repositorio
      uses: actions/checkout@v3
      
    - name: Usar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        path: ./Codigo
        node-version: '16.x'
        cache: 'npm'
        
#  test:
#    needs: build
#    runs-on: ubuntu-latest
#        
#  release:
#    needs: [build, test]
#    runs-on: ubuntu-latest
